"""
Embedding client — wraps Ollama's /api/embeddings endpoint.

CLOUD-DEPENDENCY AUDIT: This module only ever talks to `ollama_base_url`
(localhost by default). There is no fallback to any hosted embedding API.
If Ollama is unreachable, the call raises immediately — it does NOT silently
route to a cloud service.

Dense vectors are produced here. Sparse (BM25) vectors are generated by
fastembed's built-in sparse encoder at the Qdrant upsert stage (see qdrant.py),
not here — fastembed runs locally and never calls an external API.
"""

from __future__ import annotations

import asyncio
import logging
from typing import Any

import httpx
from tenacity import (
    AsyncRetrying,
    retry_if_exception_type,
    stop_after_attempt,
    wait_exponential,
)

from app.core.config import get_settings

logger = logging.getLogger(__name__)

# Maximum batch size for a single embeddings call.
# Ollama's embeddings endpoint accepts one text at a time; we batch client-side.
_BATCH_SIZE = 16


class OllamaEmbedder:
    """
    Generates dense embeddings by calling the local Ollama server.
    Retries on transient connection errors (Ollama may still be warming up).

    IMPORTANT: Never pass cloud API keys here. The `base_url` must point to
    a local Ollama instance. The config's `assert_no_cloud_keys()` is a
    belt-and-suspenders guard, but this client enforces locality too.
    """

    def __init__(self) -> None:
        settings = get_settings()
        self._base_url = settings.ollama_base_url.rstrip("/")
        self._model = settings.ollama_embed_model
        self._timeout = settings.ollama_request_timeout
        self._client = httpx.AsyncClient(
            base_url=self._base_url,
            timeout=self._timeout,
        )

    async def embed_one(self, text: str) -> list[float]:
        """Embed a single text. Returns a dense float vector."""
        async for attempt in AsyncRetrying(
            stop=stop_after_attempt(3),
            wait=wait_exponential(multiplier=1, min=1, max=8),
            retry=retry_if_exception_type(httpx.ConnectError),
        ):
            with attempt:
                resp = await self._client.post(
                    "/api/embeddings",
                    json={"model": self._model, "prompt": text},
                )
                resp.raise_for_status()
                data = resp.json()
                return data["embedding"]
        raise RuntimeError("embed_one: exhausted retries")  # unreachable but type-safe

    async def embed_batch(self, texts: list[str]) -> list[list[float]]:
        """
        Embed a list of texts. Internally batches to _BATCH_SIZE concurrent
        requests — we keep this bounded to avoid overwhelming Ollama's queue.
        """
        results: list[list[float]] = [[] for _ in texts]
        for i in range(0, len(texts), _BATCH_SIZE):
            batch = texts[i : i + _BATCH_SIZE]
            embeddings = await asyncio.gather(
                *[self.embed_one(t) for t in batch]
            )
            for j, emb in enumerate(embeddings):
                results[i + j] = emb
        return results

    async def embed_query(self, query: str) -> list[float]:
        """Convenience alias — identical to embed_one but semantically distinct."""
        return await self.embed_one(query)

    async def close(self) -> None:
        await self._client.aclose()

    async def verify_model_available(self) -> bool:
        """Check that the embedding model is pulled and ready in Ollama."""
        try:
            resp = await self._client.get("/api/tags")
            resp.raise_for_status()
            models = [m["name"] for m in resp.json().get("models", [])]
            # Ollama tags may include version suffixes, so do a prefix match
            return any(m.startswith(self._model.split(":")[0]) for m in models)
        except Exception as exc:
            logger.warning("Could not verify embedding model availability: %s", exc)
            return False


# ── Module-level singleton ────────────────────────────────────────────────────

_embedder: OllamaEmbedder | None = None


def get_embedder() -> OllamaEmbedder:
    global _embedder
    if _embedder is None:
        _embedder = OllamaEmbedder()
    return _embedder
